### PR TITLE
Replace q-io with fs-extra

### PR DESCRIPTION
**Pull request by XhmikosR**
~~@tschaub there's [one instance](https://github.com/tschaub/grunt-gh-pages/pull/82/files#diff-89fd8e8ef20565f129343f363cc8433cR92) left in this file, feel free to push a patch to this branch and then we can remove q-io :)~~

### CODE REVIEW

**Comment by XhmikosR** [comment]
I'm not sure if these are covered by the tests, but everything seems to work fine on new Node.js @tschaub. Please confirm just to be safe.

**Comment by XhmikosR** [comment]
@tschaub please check my other notifications on this repo too 🙂

Also, go ahead and merge anything you review, because if CI doesn't pass I cannot merge myself. Unless we merge #84 first.

**Comment by XhmikosR** [comment]
Oh, and if you could enable the repo option for the branches to be up to date, that would be save some time.

**Comment by tschaub** [comment]
Hello @XhmikosR.  I've initiated a transfer of this repository to you.  I'm not actively using Grunt, so don't want to block maintenance or updates to this project.  If you accept the transfer and let me know your npm username, I can add you as a maintainer of the package.

**Comment by XhmikosR** [comment]
Thanks for the offer, but I can't maintain the package either. It's just that I decided to submit a few last patches. Maybe just archive the project?

**Pull request closed without merging**
