### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by XhmikosR**
@tschaub: sorry for not splitting this, I could try splitting it if you want later.

Now, this fixes tests on Windows with autocrlf enabled, updates all the stuff and fixes a DeprecationWarning with node >= 8 when running the tests.

~~The only thing left is to replace grunt-cafe with something else.~~

Do let me know if you want me to change something and I can rebase this as needed :)

### CODE REVIEW

**Comment by XhmikosR** [comment]
If you have an ES6+ ESLint config, we should switch to that to ensure everything is compliant in the future. Not a stopper, but would be nice to have.

**Comment by tschaub** [comment]
Thanks a lot @XhmikosR!  I'll give you rights to maintain this package if you are interested.  I'd be glad to pass off responsibility for it (as I'm not an active grunt user).

**Comment by XhmikosR** [comment]
Haha, me neither :)

I just still use it in a few projects so I thought we'd tweak this.

You can add me, no problem, I just can't make any promises I'll keep contributing for a long time :)

**Comment by XhmikosR** [comment]
@tschaub: Here's the things I'd like to fix soon-ish for the next release

1. I think we should fix #75 and cut a new release, what do you think? Can you take care of that?
2. Also, how about an ES6 ESlint config? Do you have one we could use?
3. `tasks\gh-pages.js:85:5   The body of a for-in should be wrapped in an if statement to filter unwanted properties from the prototype.`
4. `tasks\gh-pages.js:122:5   Promise.then() requires 1 or 2 arguments, but received 3`

**Comment by tschaub** [comment]
I think working on #76 would provide the most benefit (remove the most code).  But feel free to prioritize as you see fit – I won't have any real time to work on this.

Regarding the ESLint config, [the current config](https://github.com/tschaub/eslint-config-tschaub/blob/v12.0.1/index.js#L9-L17) is set up for ES2018.

**Comment by XhmikosR** [comment]
Hmm, it seems the config isn't enforcing all ES6 features like no var, prefer arrow, template literals etc. Not a big deal, just wanted to make this consistent in the future.

And yeah, I agree, since you have that package, that should be the first priority and should fix of the issues I mentioned. If not we can sort them upstream and every package will benefit.

**Pull request merged**
